apiVersion: v1
kind: Service
metadata:
  name: sport-portal-backend
  namespace: sport-portal
spec:
  selector:
    app: sport-portal-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: sport-portal-frontend
  namespace: sport-portal
spec:
  selector:
    app: sport-portal-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
