apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sport-portal-ingress
  namespace: sport-portal
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sportmilliyportali.uz
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: sport-portal-backend
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sport-portal-frontend
            port:
              number: 3000
